name: CI/CD - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t santiagomachadoweb10/crud-node .

      - name: Push da imagem para o Docker Hub
        run: docker push santiagomachadoweb10/crud-node

      - name: Teste rápido da API
        run: |
          docker run -d -p 3000:3000 santiagomachadoweb10/crud-node
          sleep 5
          curl http://localhost:3000
